#
# Makefile for lge touch core driver
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_ATMEL_T1664_JP)	+= atmel_t1664.o
obj-$(CONFIG_TOUCHSCREEN_ATMEL_T1664_JP)	+= atmel_t1664_patch.o
